# Complete descriptions dictionary
# Key = setting id (sometimes also qualified by context)
# Value = human-friendly "What it does" description

SETTING_DESCRIPTIONS = {

    # ---- SHARED SECTION-LEVEL SETTINGS ----
    'heading': 'The main title displayed at the top of the section. Supports bold and italic formatting.',
    'subheading': 'A secondary line of text below the heading. Use it for a short supporting statement or tagline.',
    'paragraph': 'The main body text of the section. Supports full rich text formatting including links, lists, and bold.',
    'heading_size': 'Controls the visual size of the heading. Options are Small, Medium, Large, and Extralarge.',
    'heading_tag': 'The HTML tag used for the heading (H1, H2, H3, and so on). Use H1 only once per page, on the most important heading, as it signals the primary content to search engines.',
    'highlighted_text_enabled': 'Enables an animated highlight effect on selected words inside the heading. To apply it to a word, select it in the editor and format it as italic.',
    'highlighted_text_style': 'The style of the highlight animation. Options include Underline, Scribble underline, Text color, Thick underline, Outline, and Background color.',
    'highlighted_text_color': 'The color applied to the highlighted words in the heading.',
    'content_layout': 'Controls the horizontal alignment of the content block within the section: Left, Center, or Right.',
    'content_layout_desktop': 'Controls the horizontal alignment of the content on desktop specifically.',
    'content_layout_mobile': 'Controls the horizontal alignment of the content on mobile specifically.',
    'desktop_content_alignment': 'Controls the horizontal alignment of the text column on desktop.',
    'mobile_content_alignment': 'Controls the horizontal alignment of the text column on mobile.',
    'desktop_content_position': 'Controls the vertical position of the text block within the section on desktop: Top, Middle, or Bottom.',
    'color_scheme': 'Applies a color palette to this section, controlling the background, text, and button colors. Color palettes are defined in Theme Settings.',
    'enable_custom_background': 'When enabled, the section uses the gradient defined in the selected color palette instead of a solid background color.',
    'padding_top': 'The amount of empty space above the section content on desktop, in pixels. Increase it to separate this section visually from the one above.',
    'padding_bottom': 'The amount of empty space below the section content on desktop, in pixels.',
    'padding_top_mobile': 'The amount of empty space above the section on mobile, in pixels. Can be set independently from desktop.',
    'padding_bottom_mobile': 'The amount of empty space below the section on mobile, in pixels.',
    'button_text': 'The label displayed on the button. Leave blank to hide the button.',
    'button_url': 'The page or URL the button links to when clicked.',
    'button_link': 'The page or URL the button links to when clicked.',
    'button_style': 'The visual style of the button: Solid (filled background), Outlined (border only), or Link (text with underline).',
    'button_size': 'The size of the button: Small, Regular, Medium, Large, or Extra Large.',
    'image': 'The image displayed in this section. Click to upload or select from your media library.',
    'mobile_image': 'A separate image used on mobile screens. If left blank, the main image is used. Recommended for images that do not crop well to portrait orientation.',
    'image_ratio': 'Controls the aspect ratio of product images in this section. Options typically include Square, Portrait, Landscape, and Adapt (uses the image\'s natural ratio).',
    'image_height': 'Controls how tall the image or section appears. Choose from preset options like Small, Medium, Large, or Full screen.',
    'enable_autoplay': 'When enabled, slides advance automatically without any visitor interaction.',
    'autoplay_speed': 'How many seconds each slide stays visible before advancing to the next. Only applies when Enable autoplay is turned on.',
    'show_navigation': 'Shows or hides the navigation arrows and pagination dots that let visitors manually move between slides.',
    'show_vendor': 'Shows the product vendor (brand name) below the product title on cards.',
    'show_options': 'Displays variant options (such as color or size swatches) directly on the product card without opening the product page.',
    'quick_buy': 'Adds a quick buy button to product cards. For single-variant products it adds to cart directly. For multi-variant products it opens a small variant selector.',
    'quick_view': 'Adds a quick view button to product cards. Clicking it opens a product detail overlay without leaving the current page.',
    'no_border': 'Removes the border around product cards for a cleaner, borderless look.',
    'card_anim': 'The animation that plays when a visitor hovers over a product card. Options typically include Zoom, Slide, and None.',
    'card_content_layout': 'Controls how the product info (title, price, options) is positioned relative to the product image on cards.',
    'card_info_position': 'Controls the horizontal alignment of the product info text within the card.',
    'enable_color_swatches': 'Shows color swatches for products that have a Color or colour variant. Swatch values must be configured in Theme Settings > Color Swatch.',
    'products_row': 'The number of product columns displayed per row on desktop.',
    'products_row_mobile': 'The number of product columns displayed per row on mobile.',
    'max_products': 'The maximum number of products to display in this section.',
    'enable_carousel_desktop': 'When enabled, products are displayed in a horizontally scrollable carousel on desktop instead of a static grid.',
    'enable_carousel_mobile': 'When enabled, products are displayed in a horizontally scrollable carousel on mobile instead of a static grid.',
    'show_view_all': 'Displays a View all button at the bottom of the section that links to the full collection page.',
    'enable_filters': 'Shows the filter panel on the collection grid, allowing visitors to narrow products by available filter options.',
    'enable_sorting': 'Shows the sort dropdown on the collection grid, letting visitors reorder products by price, date, or other criteria.',
    'filters_layout': 'Controls how the filter panel is displayed. Drawer opens a slide-in panel; Sidebar shows filters in a fixed column beside the products.',
    'enable_counter': 'Shows the number of products visible given the current filters.',
    'subcategories': 'A navigation menu displayed as category tabs above the product grid. Link to collections or pages you want to use as subcategory filters.',
    'show_breadcrumbs': 'Shows breadcrumb navigation at the top of the section, helping visitors understand where they are within the store.',
    'show_breadcrumbs_mobile': 'Shows breadcrumb navigation on mobile screens. Controlled independently from the desktop breadcrumbs setting.',
    'show_tag_filter': 'Shows a tag filter bar above the article grid, letting visitors filter blog posts by tag.',
    'posts_per_page': 'The number of blog posts displayed per page before pagination appears.',
    'layout': 'Controls the overall visual layout of the section.',
    'media_aspect_ratio': 'Controls the aspect ratio of blog post images in the article grid.',
    'show_blogs_date': 'Shows the publication date on each blog post card.',
    'show_tags': 'Shows the tags associated with each blog post on the card.',
    'show_preview': 'Shows a short excerpt of the article text on the blog post card.',
    'show_image': 'Shows the article\'s featured image in the banner area at the top of the blog post.',
    'image_height_mobile': 'Controls how tall the image appears on mobile. Can be set independently from desktop.',
    'show_collection_title': 'Shows the collection name as a heading in the banner.',
    'show_collection_description': 'Shows the collection description text below the title.',
    'show_collection_image': 'Shows the collection\'s featured image as the banner background. You can override it with a custom image using the image picker below.',
    'collection_image': 'A custom image used as the banner background instead of the collection\'s default image.',
    'collection_image_height': 'Controls how tall the banner image appears.',
    'show_scrolling_text': 'Shows a scrolling text marquee below the collection title.',
    'scrolling_text': 'The text that scrolls across the section in a continuous marquee.',
    'text_size': 'Controls the font size of the scrolling text.',
    'loop_speed': 'Controls how fast the scrolling text moves. Lower values are faster.',
    'loop_direction': 'The direction in which the text scrolls: Forward (left to right) or Reverse (right to left).',
    'highlighted_column': 'Selects which column to visually highlight as the recommended or featured option.',
    'highlighted_column_color': 'The background color applied to the highlighted column.',
    'highlighted_column_text': 'A short label displayed above the highlighted column, for example "Best value" or "Most popular".',
    'table_heading': 'The text displayed in the first column header, above the feature row labels.',
    'column_1_heading': 'The heading for the first comparison column.',
    'column_1_subheading': 'A short subtitle below the first column heading.',
    'column_1_text': 'A short text line displayed below the subheading in the first column, for example a price.',
    'column_1_link': 'An optional URL for a link displayed below the text in the first column.',
    'column_1_image': 'An optional image displayed at the top of the first column.',
    'column_2_heading': 'The heading for the second comparison column.',
    'column_2_subheading': 'A short subtitle below the second column heading.',
    'column_2_text': 'A short text line displayed below the subheading in the second column.',
    'column_2_link': 'An optional URL for a link displayed below the text in the second column.',
    'column_2_image': 'An optional image displayed at the top of the second column.',
    'column_3_enabled': 'Adds a third comparison column to the table.',
    'column_3_heading': 'The heading for the third comparison column.',
    'column_3_subheading': 'A short subtitle below the third column heading.',
    'column_3_text': 'A short text line displayed below the subheading in the third column.',
    'column_3_link': 'An optional URL for a link displayed below the text in the third column.',
    'column_3_image': 'An optional image displayed at the top of the third column.',
    'content_position': 'Controls the vertical position of the content block within the section.',
    'content_image': 'An optional image displayed alongside the contact form.',
    'speed': 'Controls the scrolling speed of the marquee. Lower values are faster.',
    'direction': 'The scroll direction of the marquee: Left or Right.',
    'free_shipping_enabled': 'Shows a progress bar indicating how much more the visitor needs to spend to qualify for free shipping.',
    'enable_cross_sell': 'Shows a horizontal product list inside the cart drawer to encourage additional purchases.',
    'cross_product_list': 'The list of products to suggest in the cross-sell area of the cart drawer. Select up to the maximum supported.',
    'cross_heading': 'The heading displayed above the cross-sell product list in the cart. Renders responsively on both mobile and desktop.',
    'show_conversion_copy': 'Shows a short promotional line with an icon above the checkout button to reinforce purchase confidence.',
    'conversion_copy': 'The text shown in the conversion boost line, for example "Free returns on all orders".',
    'conversion_icon': 'The icon shown next to the conversion boost text. Choose from the available icon library.',
    'show_cart_notes': 'Shows a text input where visitors can leave a note with their order.',
    'show_discount_code': 'Shows a field where visitors can enter a discount code directly in the cart.',
    'show_view_cart_button': 'Shows a secondary button that links to the full cart page.',
    'show_checkout_button': 'Shows the main Checkout button. Disabling it prevents visitors from proceeding to checkout from the drawer.',
    'show_accelerated_checkout': 'Shows the accelerated checkout buttons (Shop Pay, Apple Pay, PayPal, and so on) below the main Checkout button, allowing visitors to skip to express payment.',
    'show_taxes_shipping_copy': 'Shows a small reassurance line below the subtotal indicating that taxes and shipping are calculated at checkout.',
    'show_payment_icons': 'Shows the accepted payment method icons (credit cards, PayPal, and so on) below the checkout button.',
    'show_terms_toggle': 'Shows a checkbox that visitors must tick to confirm they accept the terms and conditions before checkout.',
    'cart_style': 'Controls the visual style of the cart items, for example rounded or square corners.',
    'empty_message': 'The message displayed when the cart is empty.',
    'button_1_text': 'The label for the first button shown on the empty cart screen.',
    'button_1_link': 'The URL the first empty-cart button links to.',
    'button_2_text': 'The label for the second button shown on the empty cart screen.',
    'button_2_link': 'The URL the second empty-cart button links to.',
    'button_3_text': 'The label for the third button shown on the empty cart screen.',
    'button_3_link': 'The URL the third empty-cart button links to.',
    'footer_color_scheme': 'The color palette applied to the cart summary footer area (subtotal, checkout button).',
    'use_custom_colors': 'Overrides the color scheme with fully custom colors defined in the fields below.',
    'background_color': 'Custom background color for the cart drawer, used when Use custom colors is enabled.',
    'text_color': 'The color of text inside this section or block.',
    'cards_background_color': 'Custom background color for individual cart item cards.',
    'upsell_background_color': 'Custom background color for the cross-sell product area.',
    'upsell_cards_background_color': 'Custom background color for individual cross-sell product cards.',
    'upsell_button_background_color': 'Custom background color for the add button on cross-sell cards.',
    'upsell_button_text_color': 'Custom text color for the add button on cross-sell cards in the cart drawer.',
    'upsell_text_color': 'Custom text color for the cross-sell area.',
    'blog': 'Selects which blog to pull articles from. The section will automatically display the most recent posts from the selected blog.',
    'view_all': 'Shows a View all link below the article cards that navigates to the full blog page.',
    'show_blogs_date': 'Shows the publication date on each article card.',
    'rating_stars_color': 'The color of the aggregate star rating displayed at the top of the section.',
    'review_card_stars_color': 'The color of the stars displayed on individual review cards.',
    'reviews_score': 'The aggregate score to display next to the stars, for example 4.9.',
    'reviews_title': 'The text label displayed next to the aggregate score, for example "Based on 312 reviews".',
    'enable_autoplay': 'When enabled, the carousel advances automatically through slides.',
    'autoplay_speed': 'How many seconds each slide is shown before advancing. Only applies when autoplay is enabled.',
    'show_socials': 'Shows social media icons on each UGC card indicating the source platform.',
    'cards_enable_gradient': 'Adds a soft gradient overlay at the bottom of each card to improve text readability over the media.',
    'api_key': 'Your Google Maps API key. Required to load the interactive map. Generate a key in the Google Cloud Console with the Maps JavaScript API enabled.',
    'generic_markers_color': 'The color of map pin markers for locations that do not have a custom marker image.',
    'generic_markers_icon_size': 'The size of the generic map pin icons in pixels.',
    'map_bg_color': 'The background color of the map canvas, visible in areas with no roads or geography.',
    'map_roads_color': 'The color of roads and paths on the map.',
    'search_title': 'The heading displayed above the store list on the left side of the map.',
    'enable_search': 'Shows a search input that filters visible store pins based on the visitor\'s input.',
    'search_placeholder': 'The placeholder text shown inside the search input before the visitor types.',
    'height': 'Controls the height of the section.',
    'height_mobile': 'Controls the height of the section on mobile. Can be set independently from desktop.',
    'desktop_layout': 'Controls the arrangement of the product media and content column on desktop. Standard places the image on the left and the content on the right.',
    'desktop_thumb_position': 'Controls where the thumbnail strip appears relative to the main product image on desktop.',
    'show_mobile_thumbs': 'Shows thumbnail navigation below the product image on mobile.',
    'sticky_add': 'Shows a fixed bar at the bottom of the screen containing the product title and Add to cart button as the visitor scrolls.',
    'sticky_color_scheme': 'The color palette applied to the sticky add to cart bar.',
    'media_ratio': 'Controls the aspect ratio of the product media area. Auto uses the natural ratio of the first image.',
    'image_zoom': 'Controls how images behave when clicked. Lightbox opens the image in a full-screen overlay. Hover zooms in without opening a new view.',
    'enable_video_loop': 'When enabled, product videos restart automatically when they finish playing.',
    'columns': 'The number of columns in the grid on desktop.',
    'enable_mobile_scroll': 'On mobile, displays the cards in a horizontal scrollable row instead of stacking them vertically.',
    'text_alignment': 'Controls the horizontal alignment of text inside each column card on desktop.',
    'text_alignment_mobile': 'Controls the horizontal alignment of text inside each column card on mobile.',
    'icon_position': 'Controls whether icons appear above or to the left of the card text.',
    'card_columns': 'The number of icon cards displayed per row on desktop.',
    'icon_size': 'The display size of icons in pixels.',
    'icon_stroke_width': 'The stroke weight of the icon lines. Lower values produce thinner, lighter icons. Higher values produce bolder icons.',
    'icon_content_layout': 'The horizontal alignment of text within each icon card.',
    'stack_on_mobile': 'When enabled, icon cards stack vertically on mobile instead of staying in a row.',
    'desktop_image_width': 'Controls how wide the image column is relative to the text column on desktop.',
    'image_position': 'Controls whether the image appears on the left or right side of the text column.',
    'mobile_content_layout': 'Controls the alignment of text content on mobile screens.',
    'homepage_only': 'When enabled, the popup is shown only on the homepage. Disable to show it on all pages.',
    'animation_delay': 'The number of seconds after the page loads before the popup appears.',
    'expiry': 'The number of days before the popup is shown again to a visitor who has already dismissed it.',
    'cover_image': 'A background image displayed behind the popup content.',
    'close_on_overlay': 'When enabled, clicking anywhere outside the popup closes it.',
    'overlay_color': 'The color of the dark overlay behind the popup.',
    'overlay_opacity': 'How opaque the background overlay is. 0 is fully transparent, 100 is fully opaque.',
    'data_value': 'A large number displayed prominently in the section, for example 70 for a 70% discount offer.',
    'data_symbol': 'A short symbol displayed next to the data value, for example % or x or +.',
    'image_file': 'The background image for this section on desktop.',
    'image_file_mobile': 'A separate background image for mobile. If left blank, the desktop image is used.',
    'video_file': 'A background video file for desktop. Supports MP4 format. The video loops silently.',
    'video_file_mobile': 'A separate background video for mobile. If left blank, the desktop video is used.',
    'show_navigation': 'Shows the navigation arrows and pagination dots that let visitors manually move between slides.',
    'enable_autoplay': 'When enabled, the slideshow advances through slides automatically.',
    'product': 'The product to feature in this section. Select it from your store\'s product catalog.',
    'product_image': 'A custom image to display for this product instead of its default product image.',
    'show_box': 'Wraps the product image in a colored box for a cleaner, contained look.',
    'box_bg': 'The background color of the box behind the product image.',
    'box_transparency': 'How transparent the product image box is. 0 is invisible, 100 is fully solid.',
    'glass_box': 'Replaces the color box with a frosted glass effect. When enabled, the color and opacity settings are ignored.',
    'show_stars': 'Shows a star rating row above or below the heading to add social proof.',
    'stars': 'The number of stars to display. Options are 4, 4.5, and 5.',
    'stars_color': 'The color of the star icons.',
    'stars_bg_color': 'An optional background color behind the stars and following text.',
    'following_text': 'A short line of text displayed next to the stars, for example "Over 500 reviews" or "Rated 5 out of 5".',
    'following_text_color': 'The color of the text displayed next to the stars.',
    'scrolling_text_size_desktop': 'The font size of the scrolling background text on desktop, in pixels.',
    'scrolling_text_size_mobile': 'The font size of the scrolling background text on mobile, in pixels.',
    'enable_loop': 'Enables the scrolling text that runs behind the product image.',
    'images_position': 'Controls whether the product image appears on the left or right side of the section.',
    'loop_reversed': 'Controls the direction of the scrolling text. Forward scrolls left to right, Reverse scrolls right to left.',
    'enable_loop_text': 'Enables the scrolling text marquee that runs through the section.',
    'loop_text': 'The text that repeats in the scrolling marquee.',
    'bg_shape_type': 'The shape style used as a background element behind each product in the carousel.',
    'shape_color': 'The color of the background shape behind each product card.',
    'desktop_slide_width': 'Controls what percentage of the viewport width each product slide occupies on desktop. Lower values make neighboring slides more visible.',
    'mobile_slide_width': 'Controls what percentage of the viewport width each product slide occupies on mobile.',
    'wheel_animation_delay': 'The speed of the wheel rotation animation between slides. Lower values are faster.',
    'initial_text': 'A short text label displayed in the center of the carousel before a product is selected.',
    'background_text_size': 'The font size of the scrolling text in the background on desktop.',
    'background_text_opacity': 'How visible the background text is. 0 is invisible, 100 is fully opaque.',
    'background_text_spacing': 'The letter spacing of the background text, controlling how spread out the characters appear.',
    'mobile_repeat': 'When enabled, the background text is repeated to fill the full width on mobile screens.',
    'show_back_button': 'Shows a button that scrolls visitors back to the top of the page.',
    'back_button': 'The label for the back to top button.',
    'show_follow_shop': 'Shows a Follow on Shop button that lets visitors follow your store on Shopify\'s Shop app.',
    'show_policies': 'Shows links to your store policy pages (such as Privacy and Returns) at the bottom of the footer.',
    'show_currencies': 'Shows a currency selector dropdown in the footer.',
    'show_languages': 'Shows a language selector dropdown in the footer.',
    'show_payments': 'Shows the accepted payment method icons at the bottom of the footer.',
    'show_social_icons': 'Shows icons linking to your social media profiles. URLs must be set in Theme Settings > Social media.',
    'footer_type': 'Controls the layout style of the top area of the footer above the column blocks.',
    'top_image': 'An image displayed in the top area of the footer.',
    'top_text': 'A large text element displayed in the top area of the footer, for example your brand name or a tagline.',
    'top_text_animation': 'Adds a scroll-triggered animation to the top text element.',
    'logo_image': 'Your store logo image. Used in the header. You can also set a separate logo for the transparent header state.',
    'logo_desktop_size': 'The display width of the logo on desktop in pixels.',
    'logo_mobile_size': 'The display width of the logo on mobile in pixels.',
    'main_menu': 'The navigation menu displayed in the main header. Menus are created and edited in Shopify admin under Online Store > Navigation.',
    'secondary_menu': 'A secondary navigation menu displayed in the header layout or mobile drawer.',
    'header_layout': 'The layout configuration of the header navigation. Different layouts change the position of the logo, menu, and utility icons.',
    'transparent': 'When enabled, the header background is transparent only on the homepage, showing the hero section behind it.',
    'sticky': 'When enabled, the header stays fixed at the top of the viewport as the visitor scrolls.',
    'glass_scroll': 'Adds a frosted glass background to the header when the visitor scrolls down, creating a translucent overlay effect.',
    'transparent_logo_image': 'A separate logo version used when the transparent header is active. Use this to show a light-colored logo on a dark hero background.',
    'transparent_text_color': 'The color of navigation text and icons when the transparent header is active. Use a color that is readable over your hero image.',
    'blur_radius': 'The blur intensity applied to the background of the sticky header when the glass effect is enabled.',
    'cart_style': 'Controls the visual style of the cart icon in the header: a bag icon or a cart icon.',
    'enable_search': 'Shows a search icon in the header that opens a search overlay when clicked.',
    'search_color_scheme': 'The color palette applied to the search overlay.',
    'search_products_color_scheme': 'The color palette applied to the product result cards shown in predictive search.',
    'enable_social_media': 'Shows social media icons in the mobile navigation drawer.',
    'enable_language': 'Shows a language selector in the header.',
    'enable_currency': 'Shows a currency selector in the header.',
    'enable_shop_now': 'Shows a Shop now button in the desktop header, useful for driving traffic to a key collection or campaign.',
    'shop_now_cta': 'The label displayed on the Shop now button.',
    'shop_now_url': 'The URL the Shop now button links to.',
    'secondary_menu': 'A second navigation menu, displayed in the header or in a secondary navigation bar depending on the layout.',
    'sort': 'Controls the order in which collections are displayed: Alphabetical, Popularity, or other available options.',
    'collections_per_page': 'The number of collections displayed per page before pagination appears.',
    'products_page': 'The number of products displayed per page in the grid before pagination appears.',
    'columns_desktop': 'The number of columns in the product grid on desktop.',
    'columns_mobile': 'The number of columns in the product grid on mobile.',
    'show_author': 'Shows the name of the article author.',
    'show_date': 'Shows the publication date of the article.',
    'article_show_author': 'Shows the author\'s name below search result article cards.',
    'article_show_date': 'Shows the publication date below search result article cards.',
    'enable_filtering': 'Shows filters on the search results page, allowing visitors to narrow results by product type, price, or other attributes.',
    'enable_loop_text': 'Enables the scrolling text marquee that runs through the section.',
    'messages_type': 'Controls how messages are displayed: Carousel rotates through them one at a time, Marquee scrolls them continuously.',
    'marquee_message': 'The text that scrolls in the marquee when Message type is set to Marquee.',
    'marquee_speed': 'Controls how fast the marquee text scrolls. Lower values are faster.',
    'section_layout': 'Controls the desktop layout of the featured product: Standard (image left, content right) or other available options.',
    'show_tags': 'Shows the article tags below the article title.',
    'show_comments': 'Shows the comment count on the article card or banner.',

    # ---- SHARED BLOCK SETTINGS ----
    'overlay_protection': 'A dark overlay applied on top of the image to improve text readability. 0 means no overlay, 100 means fully black.',
    'content_boxed': 'Wraps the text content in a colored semi-transparent box, useful for readability on complex backgrounds.',
    'box_color': 'The fill color of the content box.',
    'box_transparency': 'How transparent the content box is. 0 is invisible, 100 is fully solid.',
    'stars_position': 'Controls where the star rating row appears relative to the other content: Above heading, Below paragraph, or Below buttons.',
    'margin_bottom': 'The space below this block in pixels on desktop. Use it to control the vertical gap between individual product page blocks.',
    'margin_bottom_mobile': 'The space below this block in pixels on mobile.',
    'default_collapse': 'When enabled, this accordion item starts closed. The visitor must click to expand it.',
    'title_size': 'The visual size of the product title heading on the product page.',
    'hide_taxes_and_shipping': 'When enabled, hides the taxes and shipping notice typically shown below the product price.',
    'show_sku': 'Shows the product SKU code below the title.',
    'show_vendor': 'Shows the product vendor (brand) name.',
    'quantity_selector': 'Shows a quantity picker so visitors can select how many units to add to cart.',
    'show_dynamic_checkout': 'Shows the dynamic checkout button (such as Buy with Shop Pay or Pay with PayPal) below the main Add to cart button.',
    'conversion_booster_copy': 'A short reassurance line displayed near the buy button, for example "Free shipping on orders over $50". Leave blank to hide.',
    'variant_type': 'Controls how variant options are displayed: as a Dropdown selector, Button pills, or Color swatches.',
    'enable_swatch': 'When enabled, displays variant buttons as color swatches using the swatch configuration from Theme Settings.',
    'low_inventory_threshold': 'The inventory quantity below which the low stock counter or bar is triggered.',
    'show_inventory_count': 'Controls when the exact inventory count is shown: Always, or only when stock is low.',
    'show_low_stock_counter': 'Shows a counter or message when the product inventory drops below the threshold.',
    'show_micro_copy': 'Shows a small urgency message on the product media area, for example "Only 3 left".',
    'micro_copy_text': 'The urgency message text displayed on the product media. Leave blank to use the default.',
    'conversion_color_scheme': 'The color palette applied to the labels and counters overlaid on the product media.',
    'inventory_text': 'The text color of the inventory label overlaid on the product media, for example "Only 3 left".',
    'inventory_bg': 'The background color of the inventory label overlaid on the product media.',
    'micro_copy_text_color': 'The text color of the micro-copy label overlaid on the product media, for example "Bestseller" or "Limited edition".',
    'micro_copy_bg': 'The background color of the micro-copy label overlaid on the product media.',
    'pairs_heading': 'The heading displayed above the Pairs well with product list.',
    'pairs_color_scheme': 'The color palette applied to the Pairs well with product cards.',
    'delay_after_purchase': 'The number of business days after the order is placed before it ships.',
    'purchase_date_tolerance': 'The number of days added to the shipping date estimate as a buffer for uncertainty.',
    'delay_after_shipping': 'The number of business days from the shipment date to expected delivery.',
    'shipping_date_tolerance': 'The number of days added to the delivery estimate as a buffer.',
    'date_format': 'Controls how the estimated delivery date is displayed, for example as a day number with month name.',
    'step_1_icon': 'The icon for the first step in the multistep trust bar. Choose from the built-in icon library.',
    'step_1_text': 'The short label for the first step, for example "Free shipping".',
    'step_2_icon': 'The icon for the second step.',
    'step_2_text': 'The short label for the second step.',
    'step_3_icon': 'The icon for the third step.',
    'step_3_text': 'The short label for the third step.',
    'row_1_icon': 'The icon for the first row in the icons with text block.',
    'row_1_heading': 'The heading for the first row.',
    'row_1_paragraph': 'The supporting description for the first row.',
    'row_2_icon': 'The icon for the second row.',
    'row_2_heading': 'The heading for the second row.',
    'row_2_paragraph': 'The supporting description for the second row.',
    'row_3_icon': 'The icon for the third row.',
    'row_3_heading': 'The heading for the third row.',
    'row_3_paragraph': 'The supporting description for the third row.',
    'bullet_points_heading': 'The heading displayed above the bullet points list.',
    'bullet_points_paragraph': 'The bullet point items. Format each point on a new line in the rich text editor.',
    'soft_background': 'When enabled, the block is wrapped in a subtle tinted background to visually separate it from the surrounding product page content.',
    'size_chart_label': 'The label for the size chart toggle button, for example "Size guide".',
    'size_chart_page': 'The Shopify page whose content is displayed in the size chart popup when clicked.',
    'accordion_heading': 'The question or label displayed in the collapsed accordion header.',
    'accordion_paragraph': 'The answer or content shown when the visitor expands this accordion item.',
    'accordion_page': 'A Shopify page whose content populates the accordion body. If set, it overrides the Paragraph field.',
    'accordion_image': 'An optional image displayed inside the accordion body when expanded.',
    'share_label': 'The text label displayed next to the social share icons.',
    'height': 'The height of this spacing block on desktop, in pixels.',
    'height_mobile': 'The height of this spacing block on mobile, in pixels.',
    'column_span': 'Controls how many columns wide this block is in the footer grid. Set to 2 for a wider block like a newsletter form.',
    'menu': 'The navigation menu displayed in this footer block. Menus are managed in Shopify admin under Online Store > Navigation.',
    'email_placeholder': 'The placeholder text shown inside the email field before the visitor types.',
    'subscribe': 'The label on the newsletter subscribe button.',
    'show_consent': 'Shows a privacy consent checkbox below the email field, required for GDPR compliance in some markets.',
    'consent': 'The consent statement text shown next to the checkbox.',
    'menu_title_apply': 'The exact label of the navigation menu item that triggers this mega menu. The match is case sensitive and must be identical to the nav item text.',
    'submenu': 'The navigation menu displayed as links inside this mega menu dropdown.',
    'shop_product_card': 'An image displayed alongside the menu links in the mega menu, for example a campaign visual.',
    'shop_product_card_url': 'The URL the mega menu image links to when clicked.',
    'collection_submenu_list': 'The collections displayed as visual cards in the mega menu.',
    'collection_submenu_cta': 'A CTA link displayed below the collection cards, for example "View all collections".',
    'product_submenu_list': 'The products displayed as visual cards in the mega menu.',
    'product_submenu_cta': 'A CTA link displayed below the product cards in the mega menu.',
    'icon': 'The icon to display in this block. Choose from the built-in icon library.',
    'icon_image': 'A custom image to use as the icon instead of a library option. SVG or PNG with transparent background recommended.',
    'info': 'Supporting text displayed below the icon and title.',
    'front_title': 'The text shown on the front face of the pill before the visitor hovers.',
    'back_title': 'The scrolling text shown on the back face of the pill on hover.',
    'main_url': 'The URL this pill navigates to when clicked.',
    'back_image': 'An image shown on the back face of the pill on hover, alongside or instead of the back text.',
    'text_outline': 'When enabled, the text is rendered in outline style (hollow letters) instead of solid fill.',
    'image_radius': 'The border radius of the image divider in pixels. Higher values produce a more rounded shape.',
    'divider_image': 'A custom image used as a visual divider between scrolling text elements.',
    'featured_image': 'A product or lifestyle image for this feature slide in the Spotlighted Product section.',
    'featured_text': 'A short scrolling text label associated with this slide.',
    'small_text': 'A small label shown above the data value, for example "Years in business" or "Happy customers".',
    'value': 'The main number for this data counter, for example 15 or 98.',
    'symbol': 'A short character shown after the number, for example %, +, or k.',
    'variant': 'The visual style of this data block: Primary (larger, featured) or Secondary (smaller, supporting).',
    'illustration': 'A decorative illustration from the built-in library shown alongside the data counter.',
    'illustration_color': 'The color applied to the built-in illustration.',
    'desktop_margin_bottom': 'The space below this FAQ item on desktop, in pixels.',
    'mobile_margin_bottom': 'The space below this FAQ item on mobile, in pixels.',
    'question': 'The question text displayed in the collapsed accordion header.',
    'answer': 'The answer text revealed when the visitor clicks to expand this item.',
    'text_bg': 'The background color of the text area within this collage block.',
    'text_layout': 'Controls the positioning of the title text within the text block.',
    'video': 'The video file for this collage block.',
    'store_image': 'An image for this store location, displayed in the location info panel.',
    'store_name': 'The name of this store location, shown in the info panel and as the map marker label.',
    'store_info': 'The address, phone number, opening hours, and other details. Supports rich text formatting.',
    'store_lat': 'The latitude of this store. Find it by right-clicking the location in Google Maps and selecting the coordinates.',
    'store_lng': 'The longitude of this store. Find it the same way as the latitude.',
    'marker_color': 'A custom color for the map pin marker of this location, overriding the global marker color.',
    'marker_icon': 'A custom image used as the map pin for this location instead of the default pin.',
    'color_text': 'The color of the label text overlaid on this side of the before-and-after slider.',
    'color_hotspot': 'The color of the hotspot circle marker on the shoppable image.',
    'horizontal': 'The horizontal position of the hotspot as a percentage (0 is the left edge, 100 is the right edge).',
    'vertical': 'The vertical position of the hotspot as a percentage (0 is the top, 100 is the bottom).',
    'horizontal_mobile': 'The horizontal hotspot position on mobile, set independently from desktop.',
    'vertical_mobile': 'The vertical hotspot position on mobile, set independently from desktop.',
    'card_link': 'The URL this UGC card links to when clicked.',
    'video_file_alt': 'Alternative text describing the video content for screen readers and accessibility.',
    'video_file_autoplay': 'When enabled, the video starts playing automatically as the card comes into view.',
    'video_file_poster': 'A cover image shown before the video starts playing.',
    'text_hover': 'When enabled, the paragraph text is hidden until the visitor hovers over the card on desktop.',
    'label': 'A short badge displayed on the card, for example "New" or "Customer review".',
    'label_background': 'The background color of the label badge.',
    'label_color': 'The text color of the label badge.',
    'slide_text': 'The full quote text for this carousel slide.',
    'slide_author': 'The name of the person being quoted.',
    'author_image': 'A photo of the reviewer displayed on the review card.',
    'author_title': 'The reviewer\'s name.',
    'author_info': 'A subtitle for the reviewer, for example their role, location, or purchase date.',
    'rating_score': 'The star rating for this review, from 1 to 5.',
    'total_score': 'The aggregate rating score shown in the section header, for example 4.9.',
    'reviews_amount': 'The total number of reviews shown next to the aggregate score, for example 312.',
    'autoplay_timer': 'How many seconds each review is displayed before the carousel advances. Only applies when autoplay is on.',
    'column_1_icon': 'The status icon for column 1 in this row: Checkmark (feature available), X (not available), or a custom text value.',
    'column_1_text': 'Custom text for column 1 in this row. If provided, it replaces the icon.',
    'column_2_icon': 'The status icon for column 2 in this row.',
    'column_2_text': 'Custom text for column 2 in this row.',
    'column_3_icon': 'The status icon for column 3 in this row.',
    'column_3_text': 'Custom text for column 3 in this row.',
    'feature_1': 'The first feature bullet point shown on this product card.',
    'feature_2': 'The second feature bullet point.',
    'feature_3': 'The third feature bullet point.',
    'feature_4': 'The fourth feature bullet point.',
    'feature_5': 'The fifth feature bullet point.',
    'glass_effect': 'Adds a frosted glass background effect to this product card.',
    'label_text': 'A short promotional label shown on the highlighted product card, for example "Best seller" or "Our pick".',
    'label_text_color': 'The text color of the promotional label.',
    'label_bg_color': 'The background color of the promotional label.',
    'scrolling_text': 'Text that scrolls in a marquee behind or alongside the product card.',
    'custom_liquid': 'Raw Liquid code injected into the page. Requires knowledge of Shopify Liquid templating.',
    'liquid': 'Raw Liquid code for this block. Requires knowledge of Shopify Liquid templating.',
    'button_action': 'What happens when this button is clicked: Close dismisses the popup, or Link navigates to the URL set below.',
    'divider_position': 'Whether the Shape Divider appears at the top or bottom of the section.',
    'divider_color_scheme': 'The color palette of the divider shape. Typically matches the section it belongs to.',
    'divider_next_color': 'The exact background color of the section immediately below this one. Setting this correctly makes the divider edge blend seamlessly.',
    'divider_style': 'The visual shape of the divider: Waves, Deep waves, Arc, Big curve, Oblique line, Triangle, or one of the shaded pattern options.',
    'bottom_left_p': 'A link label displayed in the bottom left of the section, for example "Discover more".',
    'bottom_left_p_url': 'The URL the bottom left link navigates to.',
    'bottom_left_p_style': 'The visual style of the bottom left link button: Solid, Outlined, or Link.',
    'image_height': 'Controls how tall the image appears in this section.',
    'image_height_mobile': 'Controls how tall the image appears on mobile. Can be set independently from desktop.',
    'preview_image': 'The background image for this slide on desktop.',
    'preview_image_mobile': 'A separate background image for mobile. If left blank, the desktop image is used.',
    'preview_video_file': 'The background video file for this slide on desktop. Use MP4 format for best compatibility.',
    'preview_video_file_mobile': 'A separate background video for mobile. If left blank, the desktop video is used.',
    'video_alt_text': 'Alternative text describing the video for screen readers and accessibility.',
    'bottom_title': 'A heading displayed over the foreground image on this slide.',
    'bottom_text': 'A short description shown below the heading on this slide.',
    'title_color': 'The color of the large background text element on this slide.',
    'stars_position': 'Where the star rating row appears: Above heading, Below paragraph, or Below buttons.',
    'main_image': 'The main image displayed in the foreground of this slide.',
    'product_submenu_cta': 'A CTA text displayed below the product cards in the mega menu.',
    'show_collection_image': 'Shows the collection\'s default image as the banner background. You can override it below.',
    'collection_image': 'A custom image used as the banner background instead of the collection\'s default.',
    'show_scrolling_text': 'Shows a scrolling marquee text below the collection header content.',
    'text_size': 'The font size of the scrolling text.',
    'enable_autoplay': 'When enabled, slides advance automatically.',
    'autoplay_speed': 'How many seconds each slide is shown before advancing.',
    'show_navigation': 'Shows the arrow and dot navigation controls for the slideshow.',
    'heading': 'The main heading displayed at the top of this block or section.',
    'title': 'The heading or label for this block element.',
    'paragraph': 'The body text for this block. Supports rich text formatting.',
    'enable_swatch': 'Displays variant buttons as color swatches using values configured in Theme Settings > Color Swatch.',
    'variant_type': 'How variant options are displayed: Dropdown selector, Button pills, or Color swatches.',
    'quantity_selector': 'Shows a quantity input so visitors can select how many units to add to cart.',
    'show_dynamic_checkout': 'Shows express checkout buttons like Buy with Shop Pay or Pay with PayPal below the main add to cart button.',
    'conversion_booster_copy': 'A short reassurance message near the buy button, for example "Free returns on all orders". Leave blank to hide.',
    'pairs_heading': 'The heading above the Pairs well with product list.',
    'pairs_color_scheme': 'The color palette for the Pairs well with product cards.',
    'low_inventory_threshold': 'The stock level below which the low stock indicator activates.',
    'show_inventory_count': 'Controls when to show the exact stock number: Always, or only when below the low inventory threshold.',
    'show_low_stock_counter': 'Shows a counter or urgency message when stock drops below the threshold.',
    'show_micro_copy': 'Shows a small urgency text on the product media, for example "Only 3 left in stock".',
    'micro_copy_text': 'The urgency message shown on the product media. Leave blank to use the default text.',
    'conversion_color_scheme': 'The color palette for the labels and counters overlaid on the product media.',
    'delay_after_purchase': 'Number of business days after order placement before it ships.',
    'purchase_date_tolerance': 'Buffer days added to the estimated shipping date.',
    'delay_after_shipping': 'Number of business days from shipment to delivery.',
    'shipping_date_tolerance': 'Buffer days added to the estimated delivery date.',
    'date_format': 'How the estimated date is displayed, for example as day number and month name.',
    'review_1_image': 'Photo of reviewer 1.',
    'review_1_score': 'Star rating from reviewer 1 (1 to 5).',
    'review_1_author': 'Name of reviewer 1.',
    'review_1_paragraph': 'Review text from reviewer 1.',
    'review_2_image': 'Photo of reviewer 2.',
    'review_2_score': 'Star rating from reviewer 2.',
    'review_2_author': 'Name of reviewer 2.',
    'review_2_paragraph': 'Review text from reviewer 2.',
    'review_3_image': 'Photo of reviewer 3.',
    'review_3_score': 'Star rating from reviewer 3.',
    'review_3_author': 'Name of reviewer 3.',
    'review_3_paragraph': 'Review text from reviewer 3.',
    'review_4_image': 'Photo of reviewer 4.',
    'review_4_score': 'Star rating from reviewer 4.',
    'review_4_author': 'Name of reviewer 4.',
    'review_4_paragraph': 'Review text from reviewer 4.',
    'review_5_image': 'Photo of reviewer 5.',
    'review_5_score': 'Star rating from reviewer 5.',
    'review_5_author': 'Name of reviewer 5.',
    'review_5_paragraph': 'Review text from reviewer 5.',
    'subcategories': 'A navigation menu displayed as subcategory tabs above the product grid. Set up the menu in Shopify admin under Online Store > Navigation.',
    'image_file': 'The background image for this section on desktop.',
    'image_file_mobile': 'A separate background image for mobile. If left blank, the desktop image is used.',
    'enable_loop_text': 'Enables the scrolling text marquee that runs through the section.',
    'loop_text': 'The text that repeats in the scrolling marquee.',
    'enable_carousel_desktop': 'Shows items in a horizontally scrollable carousel on desktop instead of a static grid.',
    'enable_carousel_mobile': 'Shows items in a horizontally scrollable carousel on mobile instead of a static grid.',
    'show_view_all': 'Shows a View all button below the grid linking to the full collection page.',
    'max_products': 'The maximum number of products to show in this section.',
    'products_row': 'The number of product or collection columns per row on desktop.',
    'products_row_mobile': 'The number of columns per row on mobile.',
    'products_page': 'The number of products displayed per page before pagination.',
    'card_content_layout': 'How the product info is positioned on the card relative to the image.',
    'card_info_position': 'The horizontal alignment of product info within the card.',
    'card_anim': 'The hover animation on product cards: Zoom, Slide, or None.',
    'no_border': 'Removes the border around product cards for a cleaner, borderless appearance.',
    'enable_color_swatches': 'Shows color swatches for products with a Color variant. Configure swatch values in Theme Settings.',
    'enable_filters': 'Shows the filter panel on collection or search pages.',
    'enable_sorting': 'Shows the sort dropdown on collection or search pages.',
    'enable_counter': 'Shows the count of visible products when filters are active.',
    'filters_layout': 'How the filters are displayed: Drawer (slide-in panel) or Sidebar (fixed column beside products).',
    'enable_filtering': 'Shows filters on the search results page.',
    'media_aspect_ratio': 'The aspect ratio of article images on the blog listing page.',
    'show_preview': 'Shows a short excerpt of article text on each blog card.',
    'show_blogs_date': 'Shows the publication date on each article card.',
    'show_tag_filter': 'Shows a tag filter bar above the article grid.',
    'posts_per_page': 'How many articles are shown per page before pagination appears.',
    'content_image': 'An optional image displayed alongside the contact form.',
    'data_value': 'The large number displayed prominently in the section, for example 70 for a 70% off offer.',
    'data_symbol': 'A short symbol after the number, for example %, x, or +.',
    'overlay_opacity': 'How opaque the overlay behind the popup is. 0 is fully transparent, 100 is fully visible.',
    'animation_delay': 'How many seconds after the page loads before the popup appears.',
    'expiry': 'How many days before the popup is shown again to a visitor who dismissed it.',
    'close_on_overlay': 'When enabled, clicking outside the popup closes it.',
    'homepage_only': 'When enabled, the popup only appears on the homepage.',
    'cover_image': 'A background image displayed behind the popup content.',
    'search_color_scheme': 'The color palette applied to the search overlay panel.',
    'search_products_color_scheme': 'The color palette for product cards shown in the predictive search results.',
    'enable_social_media': 'Shows social media icon links in the mobile navigation drawer.',
    'enable_language': 'Shows a language selector in the header.',
    'enable_currency': 'Shows a currency selector in the header.',
    'enable_shop_now': 'Shows a Shop now CTA button in the desktop header.',
    'shop_now_cta': 'The label on the Shop now button.',
    'shop_now_url': 'The URL the Shop now button links to.',
    'blur_radius': 'The blur intensity of the glass effect on the sticky header background, in pixels.',
    'transparent': 'When enabled, the header has a transparent background only on the homepage.',
    'transparent_logo_image': 'A separate logo used when the transparent header is active, typically a light-colored version.',
    'transparent_text_color': 'The text and icon color when the transparent header is active.',
    'glass_scroll': 'Adds a frosted glass effect to the header as the visitor scrolls down.',
    'sticky': 'When enabled, the header stays fixed at the top as the visitor scrolls.',
    'logo_mobile_size': 'The display width of the logo on mobile, in pixels.',
    'header_layout': 'The layout configuration of the header: controls the position of the logo, navigation, and utility icons.',
    'sort': 'The order in which collections are displayed on this page.',
    'collections_per_page': 'The number of collections shown per page before pagination appears.',
    'article_show_author': 'Shows the author name below article cards in search results.',
    'article_show_date': 'Shows the publication date below article cards in search results.',
    'columns_desktop': 'Number of columns in the grid on desktop.',
    'columns_mobile': 'Number of columns in the grid on mobile.',
    'show_collection_description': 'Shows the collection\'s description text below the title.',
    'show_collection_title': 'Shows the collection name as a heading in the banner.',
    'collection_image_height': 'Controls how tall the banner image appears.',
    'show_collection_image': 'Shows the collection image as the banner background.',
    'desktop_slide_width': 'How wide each slide is as a percentage of the viewport on desktop. Lower values reveal more of neighboring slides.',
    'mobile_slide_width': 'How wide each slide is on mobile as a percentage of the viewport.',
    'wheel_animation_delay': 'The speed of the wheel animation between slides. Lower values are faster.',
    'initial_text': 'Text shown in the center of the carousel before any product is selected.',
    'bg_shape_type': 'The background shape style behind each product in the carousel.',
    'shape_color': 'The color of the background shape element.',
    'background_text_size': 'The font size of the scrolling background text on desktop, in pixels.',
    'background_text_opacity': 'How visible the background text is. 0 is invisible, 100 is fully opaque.',
    'background_text_spacing': 'The letter spacing of the background text, controlling how spread out the characters appear.',
    'mobile_repeat': 'When enabled, the background text repeats to fill the full width on mobile screens.',
    'image_zoom': 'How the product image behaves on click: Lightbox opens it fullscreen, Hover zooms in on the image.',
    'enable_video_loop': 'When enabled, product videos restart automatically when they reach the end.',
    'media_ratio': 'The aspect ratio of the product media area. Auto uses the image\'s natural ratio.',
    'show_mobile_thumbs': 'Shows a thumbnail strip below the product image on mobile.',
    'desktop_thumb_position': 'Where the thumbnail strip appears relative to the main image on desktop.',
    'desktop_layout': 'The arrangement of the product image and content column on desktop.',
    'sticky_color_scheme': 'The color palette for the sticky add to cart bar.',
    'sticky_add': 'Shows a fixed bar at the bottom of the screen with the product title and Add to cart button as the visitor scrolls.',
    'footer_color_scheme': 'The color palette for the cart summary footer (subtotal and checkout button).',
    'use_custom_colors': 'Overrides the color scheme with manually set custom colors.',
    'background_color': 'A custom background color, used when Use custom colors is enabled.',
    'cards_background_color': 'Custom background color for cart item cards.',
    'upsell_background_color': 'Custom background color for the cross-sell product area.',
    'upsell_cards_background_color': 'Custom background color for cross-sell product cards.',
    'upsell_button_background_color': 'Custom background color for the add button on cross-sell cards.',
    'upsell_text_color': 'Custom text color for the cross-sell product area.',
    'enable_cross_sell': 'Shows a product suggestion row in the cart drawer to encourage additional purchases.',
    'cross_product_list': 'The products to suggest in the cross-sell area. Select them from your catalog.',
    'show_conversion_copy': 'Shows a short reassurance line with an icon above the checkout button.',
    'conversion_copy': 'The text of the reassurance line, for example "Free returns on all orders".',
    'conversion_icon': 'The icon shown next to the conversion copy line.',
    'show_cart_notes': 'Shows a text area where visitors can leave an order note.',
    'show_discount_code': 'Shows a field for entering a discount code in the cart.',
    'show_view_cart_button': 'Shows a secondary button linking to the full /cart page.',
    'show_checkout_button': 'Shows the main Checkout button.',
    'show_payment_icons': 'Shows accepted payment method icons below the checkout button.',
    'show_terms_toggle': 'Shows a checkbox visitors must accept before proceeding to checkout.',
    'cart_style': 'The visual style of the cart items (rounded or square corners).',
    'empty_message': 'The message shown when the cart is empty.',
    'button_1_text': 'The label for the first button on the empty cart screen.',
    'button_1_link': 'The URL the first empty cart button links to.',
    'button_2_text': 'The label for the second button on the empty cart screen.',
    'button_2_link': 'The URL the second empty cart button links to.',
    'button_3_text': 'The label for the third button on the empty cart screen.',
    'button_3_link': 'The URL the third empty cart button links to.',
    'free_shipping_enabled': 'Shows a progress bar indicating how close the visitor is to the free shipping threshold.',
    'rating_stars_color': 'The color of the aggregate star rating at the top of the reviews section.',
    'review_card_stars_color': 'The color of stars on individual review cards.',
    'reviews_score': 'The aggregate score displayed next to the stars, for example 4.9.',
    'reviews_title': 'The label next to the aggregate score, for example "Based on 312 reviews".',
    'show_socials': 'Shows social platform icons on UGC cards to indicate the content source.',
    'cards_enable_gradient': 'Adds a soft gradient overlay at the bottom of each card to improve text readability over the media.',
    'api_key': 'Your Google Maps API key, required to render the interactive map. Generate it in Google Cloud Console with Maps JavaScript API enabled.',
    'generic_markers_color': 'The default color of map pin markers for locations without a custom marker image.',
    'generic_markers_icon_size': 'The size of the default map pin icons in pixels.',
    'map_bg_color': 'The background color of the map canvas, visible in areas with no roads or geography.',
    'map_roads_color': 'The color of roads and paths drawn on the map.',
    'search_title': 'The heading shown above the location list on the left side of the map.',
    'enable_search': 'Shows a search input that filters the visible store pins as the visitor types.',
    'search_placeholder': 'The placeholder text shown inside the search field.',
    'image_mobile': 'A separate image for mobile. If left blank, the desktop image is used.',
    'text_alignment': 'The horizontal alignment of text inside column cards on desktop.',
    'text_alignment_mobile': 'The horizontal alignment of text inside column cards on mobile.',
    'enable_mobile_scroll': 'On mobile, displays the cards in a horizontal scrollable row instead of stacking them vertically.',
    'icon_position': 'Controls whether icons appear above or to the left of the card text.',
    'card_columns': 'The number of icon cards per row on desktop.',
    'icon_size': 'The size of the icons in pixels.',
    'icon_stroke_width': 'The stroke weight of the icon lines. Higher values produce bolder icons.',
    'icon_content_layout': 'The horizontal alignment of text within each icon card.',
    'stack_on_mobile': 'When enabled, icon cards stack vertically on mobile instead of remaining in a row.',
    'desktop_image_width': 'Controls how wide the image column is relative to the text column on desktop.',
    'image_position': 'Controls whether the image appears on the left or right side of the text column.',
    'blog': 'Selects which blog to pull recent articles from. The section automatically shows the latest posts.',
    'view_all': 'Shows a View all link below the article cards, linking to the full blog page.',
    'show_back_button': 'Shows a back to top button in the footer.',
    'back_button': 'The label text for the back to top button.',
    'show_follow_shop': 'Shows a Follow on Shop button letting visitors follow your store on the Shop app.',
    'show_policies': 'Shows links to your store policy pages at the bottom of the footer.',
    'show_currencies': 'Shows a currency selector in the footer.',
    'show_languages': 'Shows a language selector in the footer.',
    'show_payments': 'Shows accepted payment method icons at the bottom of the footer.',
    'show_social_icons': 'Shows social media icons linking to your profiles. URLs must be entered in Theme Settings > Social media.',
    'footer_type': 'The layout style of the top area of the footer, above the column blocks.',
    'top_image': 'An image displayed in the top section of the footer.',
    'top_text': 'A large text element in the top footer area, for example your brand name or tagline.',
    'top_text_animation': 'Adds a scroll animation to the top text element.',
    'logo_image': 'Your store logo used in the header. For the transparent header state, upload a separate logo below.',
    'logo_desktop_size': 'The display width of the logo on desktop, in pixels.',
    'main_menu': 'The primary navigation menu. Menus are created in Shopify admin under Online Store > Navigation.',
    'secondary_menu': 'A secondary navigation menu displayed in the header or mobile drawer.',
    'floating_header': 'When enabled, the header detaches from the page edge and floats as a rounded panel that follows the visitor as they scroll. Cannot be combined with the transparent header style.',
    'floating_border_color': 'The border color of the floating header panel.',
    'floating_border_thickness': 'The border thickness of the floating header panel, in pixels.',
    'floating_border_radius': 'The corner radius of the floating header panel, in pixels.',
    'floating_top': 'When enabled, the floating header is offset down from the top of the viewport, so it appears to hover below the page edge instead of sticking to it.',
    'show_breadcrumbs': 'Shows breadcrumb navigation helping visitors trace their path through the store.',
    'enable_breadcrumbs_collection': 'Shows breadcrumbs on collection pages.',
    'enable_breadcrumbs_product': 'Shows breadcrumbs on product pages.',
    'quick_add_color_scheme': 'The color palette applied to the quick add overlay that appears on product cards.',
    'enable_breadcrumbs_collection': 'Shows breadcrumb navigation on collection pages.',
    'enable_breadcrumbs_product': 'Shows breadcrumb navigation on product pages.',
    'enable_breadcrumbs_blog': 'Shows breadcrumb navigation on blog and article pages.',
    'currency_code_enabled': 'When enabled, the currency code (for example USD or EUR) is shown alongside prices across the store.',
    'label_font_size': 'The font size used for product card labels such as Sold out, Sale, and custom labels, in pixels.',
    'label_letter_spacing': 'The letter spacing applied to product card labels such as Sold out, Sale, and custom labels, in pixels.',
    'sold_out_label_enabled': 'Shows a Sold Out label on product cards when inventory reaches zero.',
    'sold_out_label_background_color': 'The background color of the Sold Out label.',
    'sold_out_label_text_color': 'The text color of the Sold Out label.',
    'sale_label_enabled': 'Shows a Sale label on product cards that have a compare-at price set.',
    'sale_label_background_color': 'The background color of the Sale label.',
    'sale_label_text_color': 'The text color of the Sale label.',
    'custom_label_enabled': 'Enables a custom label that can be applied to products using a metafield.',
    'custom_label_background_color': 'The background color of the custom label.',
    'custom_label_text_color': 'The text color of the custom label.',
    'animations_reveal_on_scroll': 'When enabled, sections fade and slide into view as the visitor scrolls down the page.',
    'cart_type': 'Controls how the cart is displayed: Drawer (slide-in panel), Page (full /cart page), or Popup notification.',
    'free_shipping_threshold': 'The order value at which free shipping is triggered. Enter numbers only. For multiple currencies use the format USD:100,EUR:95.',
    'free_shipping_show_truck_icon': 'Shows a truck icon inside the free shipping progress bar.',
    'free_shipping_message': 'The message shown before the threshold is reached. Use [amount] as a placeholder for the remaining amount.',
    'free_shipping_success_message': 'The message shown when the visitor has reached the free shipping threshold.',
    'free_shipping_bar_color': 'The background color of the free shipping progress bar track.',
    'free_shipping_progress_color': 'The fill color of the free shipping progress bar.',
    'free_shipping_text_color': 'The text color of the free shipping bar messages.',
    'swatch_config': 'A configuration block for mapping swatch color names to hex values or image URLs. Each line should contain the color name and its value.',
    'enable_swatch_images': 'When enabled, swatches use product images instead of solid color fills.',
    'price_color': 'A highlight color applied to product prices across the store, used to draw attention to the price.',
    'global_body_background': 'The base background color applied across the store.',
    'global_messages_success': 'The color used for success messages and notifications.',
    'global_messages_error': 'The color used for error messages.',
    'global_messages_warning': 'The color used for warning messages.',
    'color_schemes': 'The color scheme group defining all available palettes. Each scheme sets the background, text, and button colors that sections can reference.',
    'logo': 'The logo image for the store. Used as the brand mark in the header and on gift card pages.',
    'logo_width': 'The display width of the logo image, in pixels.',
    'favicon': 'The small icon shown in browser tabs and bookmarks. Recommended size is 32x32 pixels.',
    'type_header_font': 'The font used for headings across the store.',
    'heading_scale': 'The base size scale for headings. Increase to make all headings larger proportionally.',
    'heading_line_height': 'The line height of heading text. Higher values add more space between lines.',
    'heading_letter_spacing': 'The letter spacing of heading text. Higher values spread characters further apart.',
    'header_font': 'The font style used for the navigation header text.',
    'font_header_weight': 'The font weight of the navigation header text.',
    'header_scale': 'The base size scale for header navigation text.',
    'header_letter_spacing': 'The letter spacing of header navigation text.',
    'header_uppercase': 'When enabled, navigation header text is displayed in all uppercase.',
    'type_body_font': 'The font used for body text and paragraphs across the store.',
    'body_scale': 'The base size of body text. Increase to make all body text larger.',
    'body_line_height': 'The line height of body text.',
    'body_letter_spacing': 'The letter spacing of body text.',
    'type_button_font': 'The font used for button labels.',
    'buttons_scale': 'The base size of button text.',
    'buttons_letter_spacing': 'The letter spacing of button text.',
    'buttons_uppercase': 'When enabled, button text is displayed in all uppercase.',
    'blocks_border_radius': 'A global border radius setting that controls the roundness of section blocks.',
    'card_border_radius': 'The border radius applied to product and content cards.',
    'buttons_border_radius': 'The border radius applied to buttons.',
    'global_border_radius': 'A fine-grained border radius value for cards, in pixels.',
    'buttons_radius': 'A fine-grained border radius value for buttons, in pixels.',
    'max_width': 'The maximum width of the page content area in pixels. Content wider than this value is centered with side margins.',
    'page_gutter': 'The horizontal padding on either side of the page content, in pixels.',
    'global_border_thickness': 'The thickness of borders applied globally to cards and elements.',
    'buttons_border_thickness': 'The border thickness for outlined buttons, in pixels.',
    'input_border': 'The border color of form input fields.',
    'amount_2': 'The quantity for ingredient 2.',
    'amount_3': 'The quantity for ingredient 3.',
    'amount_4': 'The quantity for ingredient 4.',
    'amount_5': 'The quantity for ingredient 5.',
    'amount_6': 'The quantity for ingredient 6.',
    'amount_7': 'The quantity for ingredient 7.',
    'amount_8': 'The quantity for ingredient 8.',
    'amount_9': 'The quantity for ingredient 9.',
    'amount_10': 'The quantity for ingredient 10.',
    'amount_11': 'The quantity for ingredient 11.',
    'amount_12': 'The quantity for ingredient 12.',
    'amount_13': 'The quantity for ingredient 13.',
    'amount_14': 'The quantity for ingredient 14.',
    'amount_15': 'The quantity for ingredient 15.',
    'amount_16': 'The quantity for ingredient 16.',
    'amount_17': 'The quantity for ingredient 17.',
    'amount_18': 'The quantity for ingredient 18.',
    'amount_19': 'The quantity for ingredient 19.',
    'amount_20': 'The quantity for ingredient 20.',
    'ingredient_1': 'The name of the first ingredient, for example "Whey Protein Isolate".',
    'ingredient_2': 'The name of the second ingredient.',
    'ingredient_3': 'The name of the third ingredient.',
    'ingredient_4': 'The name of the fourth ingredient.',
    'ingredient_5': 'The name of the fifth ingredient.',
    'ingredient_6': 'The name of the sixth ingredient.',
    'ingredient_7': 'The name of the seventh ingredient.',
    'ingredient_8': 'The name of the eighth ingredient.',
    'ingredient_9': 'The name of the ninth ingredient.',
    'ingredient_10': 'The name of the tenth ingredient.',
    'ingredient_11': 'The name of the eleventh ingredient.',
    'ingredient_12': 'The name of the twelfth ingredient.',
    'ingredient_13': 'The name of the thirteenth ingredient.',
    'ingredient_14': 'The name of the fourteenth ingredient.',
    'ingredient_15': 'The name of the fifteenth ingredient.',
    'ingredient_16': 'The name of the sixteenth ingredient.',
    'ingredient_17': 'The name of the seventeenth ingredient.',
    'ingredient_18': 'The name of the eighteenth ingredient.',
    'ingredient_19': 'The name of the nineteenth ingredient.',
    'ingredient_20': 'The name of the twentieth ingredient.',
    'header_ingredient_text': 'The column header label for the ingredient name column in the table.',
    'header_amount_text': 'The column header label for the quantity/amount column in the table.',
    'table_heading_tag': 'The HTML heading tag used for the ingredients table heading (H2, H3, and so on).',
    'background': 'The background color of the highlighted product card.',
    'button_continue_text': 'The label for the secondary button on the 404 page, for example "Continue shopping".',
    'button_continue_link': 'The URL the secondary button on the 404 page links to.',
    'button_home_text': 'The label for the primary button on the 404 page, for example "Go to homepage".',
    'button_home_link': 'The URL the primary button on the 404 page links to.',
    'button_label': 'The label displayed on this button. Leave blank to hide the button.',
    'button_style_1': 'The visual style of the first button: Solid, Outlined, or Link.',
    'button_style_2': 'The visual style of the second button: Solid, Outlined, or Link.',
    'button_text_1': 'The label for the first button. Leave blank to hide it. Leave both button text fields blank to make the entire slide clickable.',
    'button_text_2': 'The label for the second button. Leave blank to hide it.',
    'button_url_1': 'The URL the first button links to.',
    'button_url_2': 'The URL the second button links to.',
    'collection': 'The collection this block represents. Select from your store catalog.',
    'column': 'The number of grid columns this block occupies in the collage layout.',
    'content': 'The main body text for this block.',
    'content_position_desktop': 'Where the text block is positioned within the slide on desktop: Top left, Middle center, Bottom right, and so on.',
    'content_position_mobile': 'Where the text block is positioned within the slide on mobile. Set independently from desktop.',
    'description': 'A short supporting text displayed below the main value or heading in this block.',
    'link': 'An optional URL this block links to when clicked.',
    'product_text': 'A short description displayed below the product name in this carousel slide.',
    'row': 'The number of grid rows this block occupies in the collage layout.',
    'sticky_image': 'A custom image displayed in the sticky (fixed) side of the section. If left blank, the product images are used.',
    'sticky_product': 'The product whose images appear in the sticky side of the section.',
    'subtitle': 'A short supporting paragraph displayed below the heading in this block.',
    'text': 'The text content for this block.',
    'video_url': 'An external video URL from YouTube or Vimeo to embed in this block.',
    'product_text': 'A short description text displayed alongside the product in this carousel slide.',
    'amount_1': 'The quantity for ingredient 1, for example "25g" or "500mg".',
    'amount_2': 'The quantity for ingredient 2.',
    'amount_3': 'The quantity for ingredient 3.',
    'amount_4': 'The quantity for ingredient 4.',
    'amount_5': 'The quantity for ingredient 5.',
    'amount_6': 'The quantity for ingredient 6.',
    'amount_7': 'The quantity for ingredient 7.',
    'amount_8': 'The quantity for ingredient 8.',
    'amount_9': 'The quantity for ingredient 9.',
    'amount_10': 'The quantity for ingredient 10.',
    'amount_11': 'The quantity for ingredient 11.',
    'amount_12': 'The quantity for ingredient 12.',
    'amount_13': 'The quantity for ingredient 13.',
    'amount_14': 'The quantity for ingredient 14.',
    'amount_15': 'The quantity for ingredient 15.',
    'amount_16': 'The quantity for ingredient 16.',
    'amount_17': 'The quantity for ingredient 17.',
    'amount_18': 'The quantity for ingredient 18.',
    'amount_19': 'The quantity for ingredient 19.',
    'amount_20': 'The quantity for ingredient 20.',
    'ingredient_1': 'The name of the first ingredient, for example "Whey Protein Isolate".',
    'ingredient_2': 'The name of the second ingredient.',
    'ingredient_3': 'The name of the third ingredient.',
    'ingredient_4': 'The name of the fourth ingredient.',
    'ingredient_5': 'The name of the fifth ingredient.',
    'ingredient_6': 'The name of the sixth ingredient.',
    'ingredient_7': 'The name of the seventh ingredient.',
    'ingredient_8': 'The name of the eighth ingredient.',
    'ingredient_9': 'The name of the ninth ingredient.',
    'ingredient_10': 'The name of the tenth ingredient.',
    'ingredient_11': 'The name of the eleventh ingredient.',
    'ingredient_12': 'The name of the twelfth ingredient.',
    'ingredient_13': 'The name of the thirteenth ingredient.',
    'ingredient_14': 'The name of the fourteenth ingredient.',
    'ingredient_15': 'The name of the fifteenth ingredient.',
    'ingredient_16': 'The name of the sixteenth ingredient.',
    'ingredient_17': 'The name of the seventeenth ingredient.',
    'ingredient_18': 'The name of the eighteenth ingredient.',
    'ingredient_19': 'The name of the nineteenth ingredient.',
    'ingredient_20': 'The name of the twentieth ingredient.',
    'header_ingredient_text': 'The column header label for the ingredient name column.',
    'header_amount_text': 'The column header label for the quantity column.',
    'table_heading_tag': 'The HTML heading tag for the ingredients table heading.',
    'background': 'The background color of the highlighted product card.',
    'button_continue_text': 'The label for the secondary button on the 404 page, for example "Continue shopping".',
    'button_continue_link': 'The URL the secondary 404 button links to.',
    'button_home_text': 'The label for the primary button on the 404 page, for example "Go to homepage".',
    'button_home_link': 'The URL the primary 404 button links to.',
    'button_label': 'The label on this button. Leave blank to hide it.',
    'button_style_1': 'The visual style of the first button: Solid, Outlined, or Link.',
    'button_style_2': 'The visual style of the second button: Solid, Outlined, or Link.',
    'button_text_1': 'The label for the first button. Leave both button text fields blank to make the entire slide clickable instead.',
    'button_text_2': 'The label for the second button. Leave blank to hide it.',
    'button_url_1': 'The URL the first button links to.',
    'button_url_2': 'The URL the second button links to.',
    'collection': 'The collection this block represents. Select from your store catalog.',
    'column': 'The number of grid columns this block spans in the collage layout.',
    'content': 'The main body text for this block.',
    'content_position_desktop': 'The position of the text block within the slide on desktop: Top left, Middle center, Bottom right, and so on.',
    'content_position_mobile': 'The position of the text block on mobile. Set independently from desktop.',
    'description': 'A short supporting text displayed below the main value or heading in this block.',
    'link': 'An optional URL this block links to when clicked.',
    'product_text': 'A short description displayed alongside the product in this carousel slide.',
    'row': 'The number of grid rows this block spans in the collage layout.',
    'sticky_image': 'A custom image for the sticky side of the section. If left blank, the product images are used.',
    'sticky_product': 'The product whose images appear in the sticky column of the section.',
    'subtitle': 'A short supporting paragraph below the heading in this block.',
    'text': 'The text content for this block.',
    'video_url': 'An external video URL from YouTube or Vimeo.',

    # ---- SOCIAL MEDIA LINKS ----
    'social_facebook_link': 'The full URL of your Facebook profile. Leave blank to hide the icon.',
    'social_twitter_link': 'The full URL of your X (formerly Twitter) profile. Leave blank to hide the icon.',
    'social_instagram_link': 'The full URL of your Instagram profile. Leave blank to hide the icon.',
    'social_youtube_link': 'The full URL of your YouTube channel. Leave blank to hide the icon.',
    'social_tiktok_link': 'The full URL of your TikTok profile. Leave blank to hide the icon.',
    'social_snapchat_link': 'The full URL of your Snapchat profile. Leave blank to hide the icon.',
    'social_pinterest_link': 'The full URL of your Pinterest profile or board. Leave blank to hide the icon.',
    'social_tumblr_link': 'The full URL of your Tumblr profile. Leave blank to hide the icon.',
    'social_linkedin_link': 'The full URL of your LinkedIn profile. Leave blank to hide the icon.',
    'social_vimeo_link': 'The full URL of your Vimeo profile. Leave blank to hide the icon.',
    'social_threads_link': 'The full URL of your Threads profile. Leave blank to hide the icon.',
    'social_whatsapp_link': 'The click-to-chat contact link for your WhatsApp account, typically in the format https://wa.me/<number>. Leave blank to hide the icon.',
    'social_discord_link': 'The invite link for your Discord server, typically in the format https://discord.gg/<code>. Leave blank to hide the icon.',
    'social_twitch_link': 'The full URL of your Twitch channel. Leave blank to hide the icon.',
    'social_messenger_link': 'The contact link for your Messenger account, typically in the format https://m.me/<page>. Leave blank to hide the icon.',
    'social_telegram_link': 'The contact link or invite URL for your Telegram account, typically in the format https://t.me/<handle>. Leave blank to hide the icon.',
    'share_email': 'Shows an email share button alongside the other social share icons, allowing visitors to send a link to the current page via their default email client.',
}
